// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Algo.
type Companyinfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Presidents           string   `protobuf:"bytes,2,opt,name=presidents,proto3" json:"presidents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Companyinfo) Reset()         { *m = Companyinfo{} }
func (m *Companyinfo) String() string { return proto.CompactTextString(m) }
func (*Companyinfo) ProtoMessage()    {}
func (*Companyinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Companyinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Companyinfo.Unmarshal(m, b)
}
func (m *Companyinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Companyinfo.Marshal(b, m, deterministic)
}
func (m *Companyinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Companyinfo.Merge(m, src)
}
func (m *Companyinfo) XXX_Size() int {
	return xxx_messageInfo_Companyinfo.Size(m)
}
func (m *Companyinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Companyinfo.DiscardUnknown(m)
}

var xxx_messageInfo_Companyinfo proto.InternalMessageInfo

func (m *Companyinfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Companyinfo) GetPresidents() string {
	if m != nil {
		return m.Presidents
	}
	return ""
}

type Ocupation struct {
	Rubro                string   `protobuf:"bytes,1,opt,name=rubro,proto3" json:"rubro,omitempty"`
	Workers              int32    `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ocupation) Reset()         { *m = Ocupation{} }
func (m *Ocupation) String() string { return proto.CompactTextString(m) }
func (*Ocupation) ProtoMessage()    {}
func (*Ocupation) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Ocupation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ocupation.Unmarshal(m, b)
}
func (m *Ocupation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ocupation.Marshal(b, m, deterministic)
}
func (m *Ocupation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ocupation.Merge(m, src)
}
func (m *Ocupation) XXX_Size() int {
	return xxx_messageInfo_Ocupation.Size(m)
}
func (m *Ocupation) XXX_DiscardUnknown() {
	xxx_messageInfo_Ocupation.DiscardUnknown(m)
}

var xxx_messageInfo_Ocupation proto.InternalMessageInfo

func (m *Ocupation) GetRubro() string {
	if m != nil {
		return m.Rubro
	}
	return ""
}

func (m *Ocupation) GetWorkers() int32 {
	if m != nil {
		return m.Workers
	}
	return 0
}

func init() {
	proto.RegisterType((*Companyinfo)(nil), "common.Companyinfo")
	proto.RegisterType((*Ocupation)(nil), "common.Ocupation")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x1c, 0xb9, 0xb8,
	0x9d, 0xf3, 0x73, 0x0b, 0x12, 0xf3, 0x2a, 0x33, 0xf3, 0xd2, 0xf2, 0x85, 0x84, 0xb8, 0x58, 0xf2,
	0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x39, 0x2e, 0xae,
	0x82, 0xa2, 0xd4, 0xe2, 0xcc, 0x94, 0xd4, 0xbc, 0x92, 0x62, 0x09, 0x26, 0xb0, 0x0c, 0x92, 0x88,
	0x92, 0x35, 0x17, 0xa7, 0x7f, 0x72, 0x69, 0x41, 0x62, 0x49, 0x66, 0x7e, 0x9e, 0x90, 0x08, 0x17,
	0x6b, 0x51, 0x69, 0x52, 0x51, 0x3e, 0xd4, 0x04, 0x08, 0x47, 0x48, 0x82, 0x8b, 0xbd, 0x3c, 0xbf,
	0x28, 0x3b, 0xb5, 0x08, 0xa2, 0x9f, 0x35, 0x08, 0xc6, 0x4d, 0x62, 0x03, 0x3b, 0xc7, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x30, 0x49, 0x5b, 0x79, 0x9e, 0x00, 0x00, 0x00,
}
