// Code generated by protoc-gen-go. DO NOT EDIT.
// source: management/iot/hardware/v1/hardwareservice_api.proto

package hardwarev1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef745ffc6a88e9a5, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EchoResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef745ffc6a88e9a5, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "management.iot.hardware.v1.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "management.iot.hardware.v1.EchoResponse")
}

func init() {
	proto.RegisterFile("management/iot/hardware/v1/hardwareservice_api.proto", fileDescriptor_ef745ffc6a88e9a5)
}

var fileDescriptor_ef745ffc6a88e9a5 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xc9, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0xcf, 0xcc, 0x2f, 0xd1, 0xcf, 0x48, 0x2c, 0x4a, 0x29,
	0x4f, 0x2c, 0x4a, 0xd5, 0x2f, 0x33, 0x84, 0xb3, 0x8b, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0xe3,
	0x13, 0x0b, 0x32, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xa4, 0x10, 0xba, 0xf4, 0x32, 0xf3,
	0x4b, 0xf4, 0x60, 0x2a, 0xf5, 0xca, 0x0c, 0xa5, 0x64, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5,
	0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x21,
	0x3a, 0x95, 0x94, 0xb9, 0xb8, 0x5d, 0x93, 0x33, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x20, 0x1c, 0x25, 0x15, 0x2e, 0x1e, 0x88, 0xa2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xec, 0xaa,
	0x8c, 0x7a, 0x18, 0xb9, 0x84, 0x3c, 0x50, 0x9d, 0xe8, 0x18, 0xe0, 0x29, 0x54, 0xc6, 0xc5, 0x02,
	0xd2, 0x2c, 0xa4, 0xae, 0x87, 0xdb, 0x91, 0x7a, 0x48, 0x6e, 0x90, 0xd2, 0x20, 0xac, 0x10, 0xe2,
	0x0e, 0x25, 0xe9, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0x89, 0x2a, 0x09, 0x80, 0x42, 0x27, 0xb5, 0x22,
	0x31, 0xb7, 0x20, 0x27, 0x55, 0x3f, 0x35, 0x39, 0x23, 0xdf, 0x8a, 0x51, 0xcb, 0xa9, 0x9d, 0x91,
	0x4b, 0x2e, 0x39, 0x3f, 0x17, 0x8f, 0x61, 0x4e, 0xe2, 0xe8, 0xce, 0x2d, 0xc8, 0x0c, 0x00, 0x85,
	0x4a, 0x00, 0x63, 0x14, 0x17, 0x4c, 0x5d, 0x99, 0xe1, 0x22, 0x26, 0x66, 0x5f, 0x4f, 0x8f, 0x55,
	0x4c, 0x52, 0xbe, 0x08, 0x93, 0x3c, 0xf3, 0x4b, 0xf4, 0x60, 0x9a, 0xf5, 0xc2, 0x0c, 0x4f, 0x21,
	0x4b, 0xc6, 0x78, 0xe6, 0x97, 0xc4, 0xc0, 0x24, 0x63, 0xc2, 0x0c, 0x93, 0xd8, 0xc0, 0x41, 0x6d,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x65, 0x3d, 0x05, 0xd9, 0xdc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HardwareserviceAPIClient is the client API for HardwareserviceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HardwareserviceAPIClient interface {
	//Doc.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type hardwareserviceAPIClient struct {
	cc *grpc.ClientConn
}

func NewHardwareserviceAPIClient(cc *grpc.ClientConn) HardwareserviceAPIClient {
	return &hardwareserviceAPIClient{cc}
}

func (c *hardwareserviceAPIClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/management.iot.hardware.v1.HardwareserviceAPI/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HardwareserviceAPIServer is the server API for HardwareserviceAPI service.
type HardwareserviceAPIServer interface {
	//Doc.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

// UnimplementedHardwareserviceAPIServer can be embedded to have forward compatible implementations.
type UnimplementedHardwareserviceAPIServer struct {
}

func (*UnimplementedHardwareserviceAPIServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}

func RegisterHardwareserviceAPIServer(s *grpc.Server, srv HardwareserviceAPIServer) {
	s.RegisterService(&_HardwareserviceAPI_serviceDesc, srv)
}

func _HardwareserviceAPI_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareserviceAPIServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/management.iot.hardware.v1.HardwareserviceAPI/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareserviceAPIServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HardwareserviceAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "management.iot.hardware.v1.HardwareserviceAPI",
	HandlerType: (*HardwareserviceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _HardwareserviceAPI_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management/iot/hardware/v1/hardwareservice_api.proto",
}
