// Code generated by protoc-gen-go. DO NOT EDIT.
// source: management/companies/user/v1/userservice_api.proto

package usersv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1b4fc2160dee1d, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EchoResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1b4fc2160dee1d, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "management.companies.users.v1.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "management.companies.users.v1.EchoResponse")
}

func init() {
	proto.RegisterFile("management/companies/user/v1/userservice_api.proto", fileDescriptor_1d1b4fc2160dee1d)
}

var fileDescriptor_1d1b4fc2160dee1d = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xca, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x4f, 0xce, 0xcf, 0x2d, 0x48, 0xcc, 0xcb, 0x4c, 0x2d,
	0xd6, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2f, 0x33, 0x04, 0xd3, 0xc5, 0xa9, 0x45, 0x65, 0x99, 0xc9,
	0xa9, 0xf1, 0x89, 0x05, 0x99, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xb2, 0x08, 0x3d, 0x7a,
	0x70, 0x3d, 0x7a, 0x60, 0xb5, 0x7a, 0x65, 0x86, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9,
	0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5,
	0x10, 0xcd, 0x4a, 0xca, 0x5c, 0xdc, 0xae, 0xc9, 0x19, 0xf9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x10, 0x8e, 0x92, 0x0a, 0x17, 0x0f, 0x44, 0x51, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x76,
	0x55, 0x46, 0x7d, 0x8c, 0x5c, 0x7c, 0xa1, 0x08, 0x17, 0x3a, 0x06, 0x78, 0x0a, 0xd5, 0x70, 0xb1,
	0x80, 0x34, 0x0a, 0x69, 0xe9, 0xe1, 0x75, 0xa3, 0x1e, 0x92, 0x13, 0xa4, 0xb4, 0x89, 0x52, 0x0b,
	0x71, 0x89, 0x92, 0x74, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0x44, 0x95, 0x04, 0x40, 0xc1, 0x93, 0x5a,
	0x91, 0x98, 0x5b, 0x90, 0x93, 0xaa, 0x9f, 0x9a, 0x9c, 0x91, 0x6f, 0xc5, 0xa8, 0xe5, 0xd4, 0xc9,
	0xc8, 0xa5, 0x98, 0x9c, 0x9f, 0x8b, 0xdf, 0x3c, 0x27, 0x61, 0x64, 0x37, 0x17, 0x64, 0x06, 0x80,
	0x82, 0x25, 0x80, 0x31, 0x8a, 0x1d, 0xac, 0xa0, 0xcc, 0x70, 0x11, 0x13, 0xb3, 0xaf, 0x73, 0xe8,
	0x2a, 0x26, 0x59, 0x5f, 0x84, 0x29, 0xce, 0x70, 0x53, 0xc0, 0x7a, 0xf5, 0xc2, 0x0c, 0x4f, 0x21,
	0xcb, 0xc7, 0xc0, 0xe5, 0x63, 0xc0, 0xf2, 0x31, 0x61, 0x86, 0x49, 0x6c, 0xe0, 0xe0, 0x36, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x72, 0x60, 0x2b, 0xe1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserserviceAPIClient is the client API for UserserviceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserserviceAPIClient interface {
	//Doc.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type userserviceAPIClient struct {
	cc *grpc.ClientConn
}

func NewUserserviceAPIClient(cc *grpc.ClientConn) UserserviceAPIClient {
	return &userserviceAPIClient{cc}
}

func (c *userserviceAPIClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/management.companies.users.v1.UserserviceAPI/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserserviceAPIServer is the server API for UserserviceAPI service.
type UserserviceAPIServer interface {
	//Doc.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

// UnimplementedUserserviceAPIServer can be embedded to have forward compatible implementations.
type UnimplementedUserserviceAPIServer struct {
}

func (*UnimplementedUserserviceAPIServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}

func RegisterUserserviceAPIServer(s *grpc.Server, srv UserserviceAPIServer) {
	s.RegisterService(&_UserserviceAPI_serviceDesc, srv)
}

func _UserserviceAPI_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserserviceAPIServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/management.companies.users.v1.UserserviceAPI/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserserviceAPIServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserserviceAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "management.companies.users.v1.UserserviceAPI",
	HandlerType: (*UserserviceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _UserserviceAPI_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management/companies/user/v1/userservice_api.proto",
}
