// Code generated by protoc-gen-go. DO NOT EDIT.
// source: management/companies/entity/v1/entityservice_api.proto

package propertyv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_983135ed5bb6dd32, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EchoResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_983135ed5bb6dd32, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "managment.companies.property.v1.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "managment.companies.property.v1.EchoResponse")
}

func init() {
	proto.RegisterFile("management/companies/entity/v1/entityservice_api.proto", fileDescriptor_983135ed5bb6dd32)
}

var fileDescriptor_983135ed5bb6dd32 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xcb, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x4f, 0xce, 0xcf, 0x2d, 0x48, 0xcc, 0xcb, 0x4c, 0x2d,
	0xd6, 0x4f, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0xd4, 0x2f, 0x33, 0x84, 0xb2, 0x8a, 0x53, 0x8b, 0xca,
	0x32, 0x93, 0x53, 0xe3, 0x13, 0x0b, 0x32, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xe4, 0xc1,
	0xfa, 0x40, 0xda, 0xf4, 0xe0, 0xda, 0x40, 0x52, 0x05, 0xa9, 0x45, 0x25, 0x95, 0x7a, 0x65, 0x86,
	0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79,
	0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0xed, 0x4a, 0xca, 0x5c, 0xdc, 0xae, 0xc9,
	0x19, 0xf9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39,
	0xa5, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x92, 0x0a, 0x17, 0x0f, 0x44,
	0x51, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x76, 0x55, 0x46, 0x53, 0x19, 0xb9, 0x04, 0x5c, 0x91,
	0x5d, 0xe9, 0x18, 0xe0, 0x29, 0xd4, 0xc0, 0xc8, 0xc5, 0x02, 0xd2, 0x2b, 0xa4, 0xa3, 0x47, 0xc0,
	0xa1, 0x7a, 0x48, 0xee, 0x90, 0xd2, 0x25, 0x52, 0x35, 0xc4, 0x41, 0x4a, 0xd2, 0x4d, 0x97, 0x9f,
	0x4c, 0x66, 0x12, 0x55, 0x12, 0x00, 0x87, 0x54, 0x45, 0x62, 0x6e, 0x41, 0x4e, 0xaa, 0x7e, 0x6a,
	0x72, 0x46, 0xbe, 0x15, 0xa3, 0x96, 0xd3, 0x14, 0x46, 0x2e, 0xe5, 0xe4, 0xfc, 0x5c, 0x42, 0x26,
	0x3a, 0x89, 0xa2, 0x3a, 0xbe, 0x20, 0x33, 0x00, 0x14, 0x42, 0x01, 0x8c, 0x51, 0x5c, 0x30, 0x55,
	0x65, 0x86, 0x8b, 0x98, 0x98, 0x7d, 0x9d, 0x03, 0x56, 0x31, 0xc9, 0xfb, 0xc2, 0x0d, 0x73, 0x86,
	0x1b, 0x16, 0x00, 0x33, 0x2c, 0xcc, 0xf0, 0x14, 0x92, 0x8a, 0x18, 0xb8, 0x8a, 0x18, 0x98, 0x8a,
	0x98, 0x30, 0xc3, 0x24, 0x36, 0x70, 0x04, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x96, 0xe3,
	0xd7, 0xde, 0xf9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EntityserviceAPIClient is the client API for EntityserviceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntityserviceAPIClient interface {
	//Doc.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type entityserviceAPIClient struct {
	cc *grpc.ClientConn
}

func NewEntityserviceAPIClient(cc *grpc.ClientConn) EntityserviceAPIClient {
	return &entityserviceAPIClient{cc}
}

func (c *entityserviceAPIClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/managment.companies.property.v1.EntityserviceAPI/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntityserviceAPIServer is the server API for EntityserviceAPI service.
type EntityserviceAPIServer interface {
	//Doc.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

// UnimplementedEntityserviceAPIServer can be embedded to have forward compatible implementations.
type UnimplementedEntityserviceAPIServer struct {
}

func (*UnimplementedEntityserviceAPIServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}

func RegisterEntityserviceAPIServer(s *grpc.Server, srv EntityserviceAPIServer) {
	s.RegisterService(&_EntityserviceAPI_serviceDesc, srv)
}

func _EntityserviceAPI_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityserviceAPIServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/managment.companies.property.v1.EntityserviceAPI/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityserviceAPIServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntityserviceAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "managment.companies.property.v1.EntityserviceAPI",
	HandlerType: (*EntityserviceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EntityserviceAPI_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management/companies/entity/v1/entityservice_api.proto",
}
